name: App Deployment

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.MY_SA_TOKEN }}
          access_token_lifetime: "300s"

      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "cluster-sbx"
          location: "us-central1-c"

      - name: Set environment variable
        run: echo "NAMESPACE=staging" >> $GITHUB_ENV

      - name: Create namespace if not exists
        run: kubectl create namespace ${{ env.NAMESPACE }} || true

      - name: Set up kubectl context
        run: kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

      - name: Deploy to Staging environment
        run: kubectl apply -f k8s-specifications/

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # needs: deploy-staging
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.MY_SA_TOKEN }}
          access_token_lifetime: "300s"

      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "cluster-sbx"
          location: "us-central1-c"

      - name: Set environment variable
        run: echo "NAMESPACE=production" >> $GITHUB_ENV

      - name: Set up kubectl context
        run: kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

      - name: Deploy to Production environment
        run: kubectl apply -f k8s-specifications/
