
name: App Deployment

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.MY_SA_TOKEN }}
          access_token_lifetime: "300s"

      - name: "Authenticate to GKE cluster"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "cluster-sbx"
          location: "us-central1-c"

      - name: Set environments
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "NAMESPACE=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
            echo "NAMESPACE=staging" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "NAMESPACE=production" >> $GITHUB_ENV
          fi  


      - name: Create namespace if not exists
        run: kubectl create namespace ${{ env.NAMESPACE }} || true

      - name: Set up kubectl context
        run: kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

      - name: Deploy to environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' || ${{ github.ref }} == 'refs/heads/staging' ]]; then
            kubectl apply -f k8s-specifications/
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            kubectl apply -f k8s-specifications/
          fi
