name: Deploy to GKE

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.MY_SA_TOKEN }}
          access_token_lifetime: "300s"

      - name: "Authenticate to GKE cluster"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "cluster-sbx"
          location: "us-central1-c"

      - name: Set environment variable for DEV
        if: github.ref == 'refs/heads/develop'
        run: echo "NAMESPACE=dev" >> $GITHUB_ENV

      - name: Set environment variable for STAGING
        if: github.ref == 'refs/heads/staging'
        run: echo "NAMESPACE=staging" >> $GITHUB_ENV

      - name: Set environment variable for PROD
        if: github.ref == 'refs/heads/main'
        run: echo "NAMESPACE=production" >> $GITHUB_ENV

      - name: Create namespace if not exists
        run: kubectl create namespace $NAMESPACE || true

      - name: Set up kubectl context
        run: kubectl config set-context --current --namespace=$NAMESPACE

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/develop'
        env:
          NAMESPACE: dev
        run: |
          kubectl apply -f k8s-specifications/

      - name: Deploy to STAGING
        if: github.ref == 'refs/heads/staging'
        env:
          NAMESPACE: staging
        run: |
          kubectl apply -f k8s-specifications/

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/prod'
        env:
          NAMESPACE: production
        run: |
          kubectl apply -f k8s-specifications/
